apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mpok5m0qv-nodejs
  janus-idp.io/tekton: mpok5m0qv-nodejs
  backstage.io/kubernetes-id: mpok5m0qv-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mpok5m0qv-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
